package com.backend.backend.parser.types;

public enum TypeEnum {
    LEFT_BRACE("{"),
    RIGHT_BRACE("}"),
    LEFT_PARANTHESIS("("),
    RIGTH_PARANTHESIS(")"),
    LEFT_SQUARED_BRACE("["),
    RIGHT_SQUARED_BRACE("]"),
    SEMICOLON(";"),
    NULL("NULL"),
    NULL_LITERAL("NULL_LITERAL"),
    NUMBER("NUMBER"),
    IDENTIFIER("IDENTIFIER"),
    SIMPLE_ASSIGN("SIMPLE_ASSIGN"),
    COMPLEX_ASSIGN("COMPLEX_ASSIGN"),
    ADDITIVE_OPERATOR("ADDITIVE_OPERATOR"),
    MULTIPLICATIVE_OPERATOR("MULTIPLICATIVE_OPERATOR"),
    STRING("STRING"),
    EMPTYSTATEMENT("EMPTYSTATEMENT"),
    BINARY_EXPRESSION("BINARY_EXPEESSION"),
    ASSIGNMENT_EXPRESSION("ASSIGNMENT_EXPRESSION"),
    LET("LET"),
    IF("IF"),
    ELSE("ELSE"),
    COMMA("COMMA"),
    VARIABLE_DECLARATION("VARIABLE_DECLARATION"),
    VARIABLE_STATEMENT("VARIABLE_STATEMENT"),
    BLOCK_STATEMENT("BLOCK_STATEMENT"),
    EXPRESSION_STATEMENT("EXPRESSION_STATEMENT"),
    IF_STATEMENT("IF_STATEMENT"),
    RELATIONAL_OPERATOR("RELATIONAL_OPERATOR"),
    EQUALITY_OPERATOR("EQUALITY_OPERATOR"),
    TRUE("TRUE"),
    FALSE("FALSE"),
    BOOLEAN_LITERAL("BOOLEAN_LITERAL"),
    LOGICAL_OR("LOGICAL_OR"),
    LOGICAL_AND("LOGICAL_AND"),
    LOGICAL_NOT("LOGICAL_NOT"),
    UNARY_EXPRESSION("UNARY_EXPRESSION"),
    CLASS_DECLARATION("CLASS_DECLARATION"),
    DO("DO"),
    WHILE("WHILE"),
    FOR("FOR"),
    WHILE_STATEMENT("WHILE_STATEMENT"),
    DO_WHILE_STATEMENT("DO_WHILE_STATEMENT"),
    FOR_STATEMENT("FOR_STATEMENT"),
    DEF("DEF"),
    RETURN("RETURN"),
    CLASS("CLASS"),
    EXTENDS("EXTENDS"),
    SUPER("SUPER"),
    NEW("NEW"),
    THIS("THIS"),
    RETURN_STATEMENT("RETURN_STATEMENT"),
    FUNCTION_DECLARATION("FUNCTION_DECLARATION"),
    MEMBER_EXPRESSION("MEMBER_EXPRESSION"),
    DOT("."),
    CALL_EXPRESSION("CALL_EXPRESSION"),
    THIS_EXPRESSION("THIS_EXPRESSION"),
    SUPER_EXPRESSION("SUPER_EXPRESSION"),
    NEW_EXPRESSION("NEW_EXPRESSION"),
    PROGRAM("PROGRAM");


    private final String representation;

    TypeEnum(String representation) {
        this.representation = representation;
    }

    public String getRepresentation() {
        return representation;
    }

    @Override
    public String toString() {
        return representation;
    }
}
